# frontend/Dockerfile.dev
FROM node:22-alpine

WORKDIR /app

# Копируем файлы зависимостей для кэширования слоев
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем исходники (но папка node_modules будет исключена через .dockerignore)
COPY . .

# Открываем порт Vite
EXPOSE 5173

# Запускаем Vite в режиме разработки
CMD ["npm", "run", "dev"]